version: "3"
services:
  graphqlapi:
    image: pjeziorowski/graphqlapi
    ports:
      - 8000:8000
    depends_on:
      - wishservice
    environment:
      - VERTX_CONFIG_PATH=conf/docker-compose.json

  wishservice:
    image: pjeziorowski/wishservice
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - VERTX_CONFIG_PATH=conf/docker-compose.json

  mongo:
    image: mongo
    ports:
      - 27017:27017
