version: "3"
services:
  graphqlapi:
    image: appwish/graphqlapi
    ports:
      - 8000:8000
    depends_on:
      - wishservice
      - voteservice
      - commentservice
    environment:
      - wishServiceHost=wishservice
      - voteServiceHost=voteservice
      - commentServiceHost=commentservice

  wishservice:
    image: appwish/wishservice
    depends_on:
      - postgres
    ports:
      - 8081:8080
    environment:
      - appHost=wishservice
      - dbHost=postgres

  voteservice:
    image: appwish/voteservice
    depends_on:
      - postgres
    ports:
      - 8082:8080      
    environment:
      - appHost=voteservice
      - dbHost=postgres

  commentservice:
    image: appwish/commentservice
    depends_on:
      - postgres
    ports:
      - 8083:8080      
    environment:
      - appHost=commentservice
      - dbHost=postgres
  web-ui:
    image: appwish/web-ui
    depends_on:
      - graphqlapi
    ports:
      - 3000:3000

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres