version: "3"
services:
  graphqlapi:
    image: appwish/graphqlapi
    ports:
      - 8000:8000
    depends_on:
      - wishservice
    environment:
      - VERTX_CONFIG_PATH=conf/docker-compose.json

  wishservice:
    image: appwish/wishservice
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - VERTX_CONFIG_PATH=conf/docker-compose.json

  web-ui:
    image: appwish/web-ui
    depends_on:
      - graphqlapi
    ports:
      - 3000:3000

  postgres:
    image: postgres
    ports:
      - 5432:5432