version: "3"
services:
  graphqlapi:
    image: appwish/graphqlapi
    ports:
      - 8000:8000
    depends_on:
      - wishservice
    environment:
      - wishServiceHost=wishservice

  wishservice:
    image: appwish/wishservice
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - appHost=wishservice
      - dbHost=postgres

  commentservice:
    image: appwish/commentservice
    depends_on:
      - postgres
    environment:
      - appHost=commentservice

  web-ui:
    image: appwish/web-ui
    depends_on:
      - graphqlapi
    ports:
      - 3000:3000

  postgres:
    image: postgres
    ports:
      - 5432:5432